services:
    cli:
        build:
            context: ../..
            dockerfile: ./docker/Dockerfile
            target: cli
        image: reilti-php-cli
        container_name: reilti-php-cli
        command: >
            sh -c \
            "composer install --optimize-autoloader
            && php artisan migrate:fresh --seed --force
            && php artisan optimize:clear"
        depends_on:
            postgres:
                condition: service_started
            redis:
                condition: service_started
        volumes:
            - ../..:/usr/src/app
        networks:
            - postgres
            - redis

    frontend:
        image: node:lts-alpine
        container_name: reilti-frontend-build
        working_dir: /usr/src/app
        command: >
            sh -c \
            "npm install
            && npm run build"
        volumes:
            - ../..:/usr/src/app

    php:
        build:
            context: ../..
            dockerfile: ./docker/Dockerfile
            target: php
        image: reilti-php
        container_name: reilti-php
        depends_on:
            cli:
                condition: service_completed_successfully
        volumes:
            - ../..:/var/www/html
        networks:
            - web
            - postgres
            - redis
            - mail
        restart: on-failure

    web:
        build:
            context: ../..
            dockerfile: ./docker/Dockerfile
            target: web
        image: reilti-web
        container_name: reilti-web
        environment:
            - FPM_HOST=reilti-php:9000
        depends_on:
            php:
                condition: service_started
        volumes:
            - ../../public:/var/www/html/public
            - ../../storage/app/public:/var/www/html/public/storage
        ports:
            - 80:80
        networks:
            - web
        restart: on-failure

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=reilti
            - POSTGRES_PASSWORD=bgm8QdLdBR9f6EwEla7U7q83
            - POSTGRES_DB=reilti
        container_name: postgres
        volumes:
            - ../../postgres-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres
        restart: on-failure

    redis:
        image: redis:alpine
        container_name: redis
        command: "redis-server --requirepass reilti"
        volumes:
            - ../../redis-volume:/data
        ports:
            - 6379:6379
        networks:
            - redis
        restart: on-failure

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 8025:8025
        networks:
            - mail

networks:
    web:
        driver: bridge
    postgres:
        driver: bridge
    redis:
        driver: bridge
    mail:
        driver: bridge
